// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig, PrismaConfig, env } from "prisma/config";

const config: PrismaConfig = {
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Always use DIRECT_URL for migrations to work
    url: env("DIRECT_URL"),
  },
};

export default defineConfig(config);
