"use client";

import { getCo2eTimelineAction } from "@/app/actions/co2e-analytics-actions";
import { Card } from "@/components/ui/card";
import { ChevronDown, ChevronUp, Leaf, Loader2 } from "lucide-react";
import { useEffect, useState } from "react";
import { Co2eTimelineChart } from "./co2e-timeline-chart";

export function Co2EmissionKpi() {
  const [isExpanded, setIsExpanded] = useState(false);
  const [timelineData, setTimelineData] = useState<Array<{
    month: string;
    cumulative: number;
    isProjected: boolean;
  }> | null>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    if (isExpanded && !timelineData) {
      loadTimelineData();
    }
  }, [isExpanded]);

  async function loadTimelineData() {
    setLoading(true);
    setError(null);
    const result = await getCo2eTimelineAction();
    if ("error" in result) {
      setError(result.error ?? "Failed to load timeline data");
    } else {
      setTimelineData(result.data);
    }
    setLoading(false);
  }

  return (
    <Card className="p-6 shadow-soft transition-all duration-200">
      <button
        onClick={() => setIsExpanded(!isExpanded)}
        className="w-full flex items-center justify-between text-left"
      >
        <div className="flex items-center gap-3">
          <div className="h-10 w-10 rounded-lg bg-emerald-100 dark:bg-emerald-900/20 flex items-center justify-center">
            <Leaf className="h-5 w-5 text-emerald-600 dark:text-emerald-400" />
          </div>
          <div>
            <h2 className="font-heading text-xl font-semibold">
              Total CO2 Emissions
            </h2>
            <p className="text-sm text-muted-foreground">
              Track carbon footprint from cloud operations
            </p>
          </div>
        </div>
        {isExpanded ? (
          <ChevronUp className="h-5 w-5 text-muted-foreground" />
        ) : (
          <ChevronDown className="h-5 w-5 text-muted-foreground" />
        )}
      </button>

      {isExpanded && (
        <div className="mt-6 space-y-6 animate-in fade-in duration-200">
          <div>
            <p className="text-muted-foreground leading-relaxed">
              Total CO₂ emissions represent the absolute greenhouse gas
              emissions generated by an organisation’s cloud operations over a
              defined period. This KPI is significant because it reflects the
              direct environmental impact of digital infrastructure on the
              climate, contributing to global warming and associated ecosystem
              stress. It is typically calculated by applying provider- or
              region-specific emission factors to cloud usage data (such as
              compute, storage, and data transfer) and aggregating the resulting
              CO₂e values. A decrease in total emissions indicates that the
              organisation is reducing its overall environmental footprint
              through actions such as workload optimisation, cleaner regions, or
              more efficient services. From a lender’s perspective, this KPI
              demonstrates material impact, comparability over time, and
              accountability, especially when measured against a fixed baseline
              or emissions cap aligned with broader decarbonisation targets.
            </p>
          </div>

          <div className="pt-4 border-t">
            <h3 className="font-heading text-lg font-semibold mb-4">
              Performance Analytics
            </h3>
            {loading && (
              <div className="bg-muted/50 rounded-lg p-8 text-center">
                <Loader2 className="h-8 w-8 animate-spin text-muted-foreground mx-auto mb-2" />
                <p className="text-muted-foreground">
                  Loading timeline data...
                </p>
              </div>
            )}
            {error && (
              <div className="rounded-md bg-destructive/15 p-3 text-sm text-destructive">
                {error}
              </div>
            )}
            {timelineData && !loading && !error && (
              <Co2eTimelineChart data={timelineData} />
            )}
          </div>
        </div>
      )}
    </Card>
  );
}
