"use client";

import { getCo2eTimelineAction } from "@/app/actions/kpi/co2e-analytics-actions";
import { Leaf } from "lucide-react";
import { BaseKpiCard } from "./base-kpi-card";
import { Co2eTimelineChart } from "./co2e-timeline-chart";

export function Co2EmissionKpi() {
  return (
    <BaseKpiCard
      title="Total CO2 Emissions"
      subtitle="Track carbon footprint from cloud operations"
      icon={Leaf}
      longDescription="Total CO₂ emissions represent the absolute greenhouse gas
              emissions generated by an organisation’s cloud operations over a
              defined period. This KPI is significant because it reflects the
              direct environmental impact of digital infrastructure on the
              climate, contributing to global warming and associated ecosystem
              stress. It is typically calculated by applying provider- or
              region-specific emission factors to cloud usage data (such as
              compute, storage, and data transfer) and aggregating the resulting
              CO₂e values. A decrease in total emissions indicates that the
              organisation is reducing its overall environmental footprint
              through actions such as workload optimisation, cleaner regions, or
              more efficient services. From a lender’s perspective, this KPI
              demonstrates material impact, comparability over time, and
              accountability, especially when measured against a fixed baseline
              or emissions cap aligned with broader decarbonisation targets."
      fetchAction={getCo2eTimelineAction}
      renderAnalytics={(data) => <Co2eTimelineChart data={data} />}
    />
  );
}
