Resources:
  CCFRole:
    Type: 'AWS::IAM::Role'
    Description: This role allows Cloud Carbon Footprint application to read CloudWatch and Cost Explorer data from AWS
    Properties:
      RoleName: 'ccf'
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              AWS: 'arn:aws:iam::869442501222:user/ccf'
            Action: sts:AssumeRole
      Policies:
        - PolicyName: cloudwatch
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - cloudwatch:GetMetricData
                  - cloudwatch:GetMetricStatistics
                Resource: '*'
        - PolicyName: cost-explorer
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - ce:GetCostAndUsage
                Resource: '*'
        - PolicyName: lambda-logs
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - logs:DescribeLogGroups
                  - logs:StartQuery
                Resource: !Sub 'arn:aws:logs:*:${AWS::AccountId}:log-group:*'
              - Effect: Allow
                Action:
                  - logs:GetQueryResults
                  - logs:StopQuery
                  - logs:DescribeQueries
                Resource: '*'

Outputs:
  RoleArn:
    Description: "ARN of the IAM role to be assumed by GreenRatchet."
    Value: !GetAtt CCFRole.Arn
    Export:
      Name: "Role ARN"
  ExternalId:
    Description: "The External ID required by GreenRatchet to assume this role."
    Value: !Ref ExternalId
    Export:
      Name: "External ID"
